language: objective-c
cache: cocoapods

before_install:
  # - brew update
  # - brew outdated xctool || brew upgrade xctool
  - ./.travis-before-install.sh
# before_script:
#   - swiftlint
script:
  - swiftlint
  - xctool -workspace travis-test.xcworkspace -scheme travis-test -sdk iphonesimulator9.2 build test